#ifndef NETWORKNODE_H
#define NETWORKNODE_H

namespace NetworkNode {

enum Register
{
	REGISTER_ID,
	REGISTER_VERSION,
	REGISTER_PRECISION,
	REGISTER_MAC_ADDRESS,
	REGISTER_PACKET_SIZE,
	REGISTER_PACKET_INTERVAL,
	REGISTER_PACKET_DST,
	REGISTER_CUSTOM_PACKET,
	REGISTER_BANDWIDTH_IN,
	REGISTER_BANDWIDTH_OUT
};

enum Command
{
	CMD_GET_ID              = 0x00,
	CMD_GET_VERSION         = 0x01,
	CMD_GET_PRECISION       = 0x02,
	CMD_GET_MAC_ADDRESS     = 0x03,
	CMD_GET_PACKET_SIZE     = 0x04,
	CMD_GET_PACKET_INTERVAL = 0x05,
	CMD_GET_PACKET_DST      = 0x06,
	CMD_GET_CUSTOM_PACKET   = 0x07,
	CMD_GET_BANDWIDTH_IN    = 0x08,
	CMD_GET_BANDWIDTH_OUT   = 0x09,

	CMD_SET_PACKET_SIZE     = 0x44,
	CMD_SET_PACKET_INTERVAL = 0x45,
	CMD_SET_PACKET_DST      = 0x46,
	CMD_SET_CUSTOM_PACKET   = 0x47,

	CMD_LOAD_CUSTOM_DATA    = 0x87,

	CMD_MEASUREMENTS        = 0xC0
};

}

#endif // NETWORKNODE_H
